In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Machine Learning - Model Evaluation & Linear Regression Gradient Descent

## 1. Model Evaluation
### - Hold-out Evaluation

In [ ]:
# load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
df = pd.read_csv(url, sep=';')

In [ ]:
# show data using head()
df.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  
0      9.4        5  
1      9.8        5

In [ ]:
# shuffle the data # 꼭 필요한 과정~
df_shuffle = df.sample(frac=1, random_state=23) # frac :   # random_state : 시드값

In [ ]:
df_shuffle

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1596            6.3             0.510         0.13             2.3      0.076   
201             8.8             0.370         0.48             2.1      0.097   
167             7.3             0.550         0.03             1.6      0.072   
1011            8.9             0.320         0.31             2.0      0.088   
604             8.3             0.580         0.13             2.9      0.096   
...             ...               ...          ...             ...        ...   
1512            6.4             0.790         0.04             2.2      0.061   
950             8.9             0.120         0.45             1.8      0.075   
1064            8.2             0.740         0.09             2.0      0.067   
742             6.5             0.615         0.00             1.9      0.065   
595             8.9             0.595         0.41             7.9      0.086   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1596                 29.0                  40.0  0.99574  3.42       0.75   
201                  39.0                 145.0  0.99750  3.04       1.03   
167                  17.0                  42.0  0.99560  3.37       0.48   
1011                 12.0                  19.0  0.99570  3.17       0.55   
604                  14.0                  63.0  0.99840  3.17       0.62   
...                   ...                   ...      ...   ...        ...   
1512                 11.0                  17.0  0.99588  3.53       0.65   
950                  10.0                  21.0  0.99552  3.41       0.76   
1064                  5.0                  10.0  0.99418  3.28       0.57   
742                   9.0                  18.0  0.99720  3.46       0.65   
595                  30.0                 109.0  0.99980  3.27       0.57   

      alcohol  quality  
1596     11.0        6  
201       9.3        5  
167       9.0        4  
1011     10.4        6  
604       9.1        6  
...       ...      ...  
1512     10.4        6  
950      11.9        7  
1064     11.8        6  
742       9.2        5  
595       9.3        5  

[1599 rows x 12 columns]

In [ ]:
# select features "fixed acidity", "volatile acidity", "chlorides"
A = df_shuffle[["fixed acidity", "volatile acidity", "chlorides"]]
A.insert(0, 'intercept', 1)
A = A.to_numpy()

In [ ]:
# show data
A

array([[1.   , 6.3  , 0.51 , 0.076],
       [1.   , 8.8  , 0.37 , 0.097],
       [1.   , 7.3  , 0.55 , 0.072],
       ...,
       [1.   , 8.2  , 0.74 , 0.067],
       [1.   , 6.5  , 0.615, 0.065],
       [1.   , 8.9  , 0.595, 0.086]])

In [ ]:
# convert to numpy arrays
b = df_shuffle["quality"].to_numpy()

In [ ]:
# hold-out evaluation: 80 for training / 20 for test
x_train = A[:1400]
y_train = b[:1400]
x_test = A[1400:]
y_test = b[1400:]

In [ ]:
# train the model with normal equation
x_hat = np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train

In [ ]:
# error = b - A x_hat
error = y_test - x_test @ x_hat
error

array([ 5.37931236e-01, -8.42831323e-01,  2.45394589e-01,  1.32564306e+00,
       -5.72191383e-02, -5.12725428e-01, -5.62897641e-02, -9.34289032e-01,
        1.84532230e-01, -9.38977059e-03, -1.55794116e-02, -6.79544527e-01,
        1.09376151e+00,  2.88129417e-01,  9.16496877e-01,  1.27063646e+00,
       -5.36296744e-01,  5.90871244e-01, -7.40154206e-01,  8.46902246e-02,
       -2.00727114e-01, -5.14751872e-01, -5.19547194e-01,  9.84941227e-01,
        4.56936873e-01, -5.65992151e-01,  4.64224100e-01, -5.80668493e-01,
        4.54435834e-01,  3.52410313e-01,  7.77171657e-01, -3.46333530e-02,
        5.97065207e-02,  4.18699382e-01, -9.50499210e-01,  3.95527977e-01,
       -4.13589460e-01, -4.14389023e-01,  6.20298354e-01, -1.69158770e+00,
        1.64809566e-01,  4.72199092e-01, -8.11396297e-01,  4.10557466e-01,
        1.01325166e+00,  9.55514579e-01, -3.58436010e-01,  1.10168138e+00,
        4.23625287e-01,  3.78159502e-01, -7.00568297e-01, -1.04952312e+00,
        8.84299605e-01, -

In [ ]:
# MSE
MSE = error.T @ error
MSE = MSE / len(y_test)

In [ ]:
# "Model 1" MSE
MSE


0.5800827732694251

Suppose we want to compare two models "Model 1" and "Model 2",

- "Model 1" is using "fixed acidity", "volatile acidity", "chlorides" for prediction of "quality".
- "Model 2" is using "residual sugar", "free sulfur dioxide", "chlorides" for prediction of "quality".

We can evaluate model performances with MSE.

In [ ]:
# feature selection
A = df_shuffle[["residual sugar", "free sulfur dioxide", "chlorides"]]
A.insert(0, "intercept", 1)

In [ ]:
# convert to numpy arrays
A = A.to_numpy()
b = df_shuffle[["quality"]].to_numpy()

In [ ]:
# hold-out tech. train and test 80/20
x_train = A[:1400]
y_train = b[:1400]
x_test = A[1400:]
y_test = b[1400:]

In [ ]:
# train the model
x_hat = np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train

In [ ]:
# error = b - A x_hat
error = y_test - x_test @ x_hat

In [ ]:
# "Model 2" MSE
MSE = error.T @ error
MSE = MSE / len(x_test)

In [ ]:
MSE

array([[0.62398506]])

Therefore, "Model 1" has better prediction than "Model 2" in terms of MSE using hold-out evaluation.

## - k-fold cross-validation

Suppose we split dataset into 5-folds, and want to evaluate "Model 1"
- Model 1: "fixed acidity", "volatile acidity", "chlorides" for features, and "quality" for prediction variable

In [ ]:
# select features "fixed acidity", "volatile acidity", "chlorides"
A = df_shuffle[["fixed acidity", "volatile acidity", "chlorides"]]
A.insert(0, 'intercept', 1)

In [ ]:
# convert to numpy arrays
A = A.to_numpy()
b = df_shuffle['quality'].to_numpy()

In [ ]:
# create 5-fold cross_validation function
k = 5
def cross_validation(k, A, b):
  num_data = len(A) # 총데이터
  idx = num_data // k # 한 인덱스
  idx_set = [0, idx, 2*idx, 3*idx, 4*idx, num_data]
  total_MSE = 0
  for i in range(len(idx_set)-1):
    # train set 인덱스 부분 합치기
    x_train = np.concatenate((A[:idx_set[i]], A[idx_set[i+1]:]))
    y_train = np.concatenate((b[:idx_set[i]], b[idx_set[i+1]:]))

    # test set 부분
    x_test = A[idx_set[i]:idx_set[i+1]]
    y_test = b[idx_set[i]:idx_set[i+1]]

    # 앞의 예제와 같은 계산 과정
    x_hat = np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train
    error = y_test - x_test @ x_hat
    MSE = error.T @ error / len(x_test)
    total_MSE += MSE

  avg_MSE = total_MSE / k

  return avg_MSE

In [ ]:
# test the function for model 1
cross_validation(k, A, b)

0.5471914183865738

Next, on Model 2, where the linear model is "residual sugar", "free sulfur dioxide", "chlorides" for features and predict "quality".
- Use cross_validation with k=5 and compare with the previous result

In [ ]:
# model 2 feature selection
A = df_shuffle[["residual sugar", "free sulfur dioxide", "chlorides"]]
A.insert(0, "intercept", 1)

In [ ]:
# to numpy arrays
A = A.to_numpy()
b = df_shuffle[["quality"]].to_numpy()

In [ ]:
# cross validation for model 2
cross_validation(k, A, b)

array([[0.64260383]])

# 2. Feature Engineering

In [ ]:
# Use pd.read_csv() to load the house price dataset from the URL.
url = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv"
df = pd.read_csv(url)

In [ ]:
df.head(2)

In [ ]:
# suppose person_per_bed = population / total_bedrooms which is how many people use one bedroom is the crucial feature for determining the house price


In [ ]:
df.head(2)

# 3. Feature Scaling

One way of feature scaling is max normalization where you can scale data by the maximum value.

In [ ]:
# get a maximum value from median_house_value in house price dataset
max_value = df["median_house_value"].max()
max_value

KeyError: ignored

In [ ]:
# you can normalize median_house_value
df["median_house_value"] # 데이터를 최대한 0과 1 사이에 scaling 시킴~

In [ ]:
df

# 4. Linear Regression with 1 feature (Gradient Descent)

Suppose we want to perform simple linear regression on weight and height data. Let us start with very simple synthetic data.

In [ ]:
# let's get our training data
x_train = np.array([62, 64, 68, 72, 80, 85])
y_train = np.array([166,173, 172, 180, 176, 185])

In [ ]:
# plot our data on 2-dimension xy-plane


# labels and title



In linear regression,

1.   model: $f_{wb} = wx + b$
2.   parameter: $w, b$
3.   cost function: $J(w, b)$
4.   objective: $min_{w,b} J(w,b)$



In [ ]:
# define our function (or hypothesis)
def linear_function(w, b, x):
  return

In [ ]:
# check if our function works
linear_function(1, 100, x_train[0])

In linear regression, we define cost function as squared error:


$J(w,b) = 1/2m \sum_{i=1}^{m} (f_{wb}(x^{(i)}) - y^{(i)})^2$

In [ ]:
# define cost function
def cost_model(w, b, x, y):
  '''
  Args:
    model param: w, b
    input training data: x, y
  Return:
    cost: J_wb
  '''
  # initialize cost J_wb
  J_wb = 0

  # compute cost given w, b


  return


In [ ]:
cost_model(1, 100, x_train, y_train)

Let us draw our initial model and its cost function with respect to $w$

In [ ]:
# our predicted value with w = 1, b = 100


In [ ]:
# plot our data on 2-dimension xy-plane

# labels and title

# our legend



In [ ]:
# cost function J_w with respect to w only
J_w = np.zeros(20)
w = np.linspace(0.5,  1.5, 20)
for i in range(20):
  J_w[i] = cost_model(w[i], 100, x_train, y_train)

# print cost function J_w
J_w

In [ ]:
# plot J_w
plt.plot(w, J_w)

Implement our learning algorithm - gradient descent algorithm where

$dJ / dw = 1/m \sum_{i=1}^{m} (f_{wb}(x^{(i)}) - y^{(i)}) * x^{(i)}$ and

$dJ / db = 1/m \sum_{i=1}^{m} (f_{wb}(x^{(i)}) - y^{(i)})$

In [ ]:
# define gradient function w.r.t w
def compute_grad_w(w, b, x, y):
  '''
    Args:
      param: w, b
      training data: x, y
    Return:
      dJ_dw
  '''

  return

In [ ]:
# check if our function works
compute_grad_w(100, 1, x_train, y_train)

In [ ]:
# define gradient function w.r.t b
def compute_grad_b(w, b, x, y):
  '''
    Args:
      param: w, b
      training data: x, y
    Return:
      dJ_db
  '''

  return

In [ ]:
# check if our function works
compute_grad_b(100, 1, x_train, y_train)

In [ ]:
# gradient descent algorithm
def grad_descent(x, y):
  '''
    Args:
      training data: x, y
    Returns:
      params: w, b
      cost: J
  '''
  # create param w, b

  # initialize w and b

  # learning rate (alpha) and convergence ratio (epsilon)
  alpha = 0.0001
  epsilon = 0.001

  # repeat procedure until convergence

  return w, b, J


In [ ]:
# compute gradient descent to obtain optimal paramters w and b, and number of iterations t
w_trace, b_trace, J = grad_descent(x_train, y_train)

In [ ]:
# let look at the history of w
w_trace

In [ ]:
# let look at the history of b
b_trace